// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "witch_idle_1":return img`
..............................
..............................
..............................
..........1111................
........111bb111..............
......111bbbbbb11.............
.....11bbbbbbbbb111...........
....11bbbbbbbbbbbb11..........
...11bbbbbbbbbbbbbbb111.......
...1bbb111bbbbbbbccbbb1.......
...11111111bbbbcccccc11.......
........111bbbccc7ccc1........
........1bbbbcc777fc11........
.......11bbbcc77f777711.......
.......1bbbcce777777771.......
.......1bbccce7777e1111.......
.......11111ee772ee1..........
..........11eeccce11..........
..........1eeccccc1...........
..........1eccbbcc11..........
..........11bbbbbcc1..........
...........1bbbbbcc1..........
...........1bbbbbcc1..........
..........11bbbbbcc1..........
..........1bbbbbbcc1..........
.........11bbbbbbcc1..........
.........1bbbbbbccc11.........
.........1bbbbbbcccc1.........
.........1bbbbbbcccc1.........
........11bbbbbbcccc1.........
........1bbbbbbbcccc1.........
........1bbbbbbccccc11........
........1bbbbbbcccccc1........
........1bbbbbccccccc1........
........1bbbbcccccccc1........
........11bcccccccc111........
.........11111111111..........
..............................
..............................
..............................
`;
            case "image2":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
